name = "TwoDimensionalLambdaCalculus"
version = "0.1.0"
defaultTargets = ["TwoDimensionalLambdaCalculus", "Challenge", "Solution", "ExtensionChallenge", "Extensions", "SubmissionChallenge"]

[[lean_lib]]
name = "TwoDimensionalLambdaCalculus"
roots = ["TwoDimensionalLambdaCalculus"]

[[lean_lib]]
name = "Challenge"
roots = ["Challenge"]

[[lean_lib]]
name = "Solution"
roots = ["Solution"]

[[lean_lib]]
name = "Syntax"
roots = ["Syntax"]

[[lean_lib]]
name = "Refutation"
roots = ["Refutation"]

[[lean_lib]]
name = "Extensions"
roots = ["Extensions"]

[[lean_lib]]
name = "ExtensionChallenge"
roots = ["ExtensionChallenge"]

[[lean_lib]]
name = "SubmissionChallenge"
roots = ["SubmissionChallenge"]
