import Solution

#print axioms TDLC.evalHomotopyStepI
#print axioms TDLC.evalHomotopyStepI_refl
#print axioms TDLC.evalHomotopyStepI_beta
#print axioms TDLC.evalHomotopyStepI_eta
#print axioms TDLC.evalHomotopyStepI_apCong
#print axioms TDLC.evalHomotopyStepI_sym
#print axioms TDLC.evalHomotopyStepI_trans
#print axioms TDLC.evalHomotopyStepI_lamCong
#print axioms TDLC.certifiedStepNaturality
#print axioms TDLC.evalHomotopyPathI
#print axioms TDLC.evalHomotopyPathI_nil
#print axioms TDLC.evalHomotopyPathI_seq
#print axioms TDLC.certifiedPathNaturality
#print axioms TDLC.transportAlongPresented
#print axioms TDLC.transportAlongPresentedRespects
#print axioms TDLC.certifiedTransport
#print axioms TDLC.recoverNaturalityFromTransport
#print axioms TDLC.certifiedNaturalityViaTransport
#print axioms TDLC.transportAlongPathI
#print axioms TDLC.transportAlongPathI_nil
#print axioms TDLC.transportAlongPathI_seq
#print axioms TDLC.transportAlongPathIRespects
#print axioms TDLC.certifiedPathTransport
#print axioms TDLC.recoverNaturalityFromPathTransport
#print axioms TDLC.certifiedPathNaturalityViaTransport
#print axioms TDLC.evaluatedHeadTagConstant
#print axioms TDLC.semanticFamilyNotPresented
#print axioms TDLC.Path.parity_lEmbed
#print axioms TDLC.Path.parity_concat
#print axioms TDLC.Path.parity_inv
#print axioms TDLC.Path.parity_ap
#print axioms TDLC.step2PreservesParity
#print axioms TDLC.path2PreservesParity
#print axioms TDLC.betaEtaSeparated
#print axioms TDLC.betaEtaLoopNontrivial
